### ISSUE TITLE
Tests for react components

### ISSUE THREAD

**Issue by veelenga** [veelenga/cybfootball#27]
Would be nice to have to lock changes and prevent issues during upgrade:
https://facebook.github.io/jest/docs/tutorial-react.html

**Comment by Tetramputechture** [comment]
Any updates on getting Jest and react-rails to play nicely? I stumbled onto this and it's been a downward spiral of messy imports and requires everywhere.

**Comment by veelenga** [comment]
@Tetramputechture oh sorry, but no, there are no updates. This project is a bit abounded now.
